# Generated by Django 2.1.2 on 2018-11-02 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='industry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_name', models.CharField(max_length=264, unique=True)),
                ('category', models.CharField(max_length=264, unique=True)),
                ('date', models.DateField()),
            ],
        ),
    ]
