# Generated by Django 2.1.2 on 2018-11-02 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('searchBarApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='industry',
            name='website_url',
            field=models.URLField(default='url', unique=True),
        ),
    ]
