# Generated by Django 2.1.2 on 2018-11-03 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('searchBarApp', '0003_auto_20181103_0111'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='industry',
            name='website_url',
        ),
        migrations.AlterField(
            model_name='industry',
            name='category',
            field=models.CharField(max_length=264),
        ),
    ]
