# Generated by Django 2.1.2 on 2018-11-03 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('searchBarApp', '0004_auto_20181104_0110'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='industry',
            name='date',
        ),
        migrations.RemoveField(
            model_name='industry',
            name='category',
        ),
        migrations.AddField(
            model_name='industry',
            name='about',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='industry',
            name='category',
            field=models.CharField(default='', max_length=264),
        ),
        migrations.AddField(
            model_name='industry',
            name='date_established',
            field=models.DateField(default=''),
        ),
    ]
