# Generated by Django 2.1.2 on 2018-11-03 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('searchBarApp', '0005_auto_20181104_0148'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='industry',
            name='about',
        ),
        migrations.RemoveField(
            model_name='industry',
            name='category',
        ),
        migrations.RemoveField(
            model_name='industry',
            name='date_established',
        ),
        migrations.AddField(
            model_name='industry',
            name='About',
            field=models.CharField(default='', max_length=264),
        ),
        migrations.AddField(
            model_name='industry',
            name='date',
            field=models.DateField(default=''),
        ),
        migrations.AddField(
            model_name='industry',
            name='category',
            field=models.CharField(default='', max_length=264),
        ),
    ]
