# Generated by Django 2.1.2 on 2018-11-03 21:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('searchBarApp', '0008_auto_20181104_0235'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='industry',
            name='date',
        ),
    ]
