# Generated by Django 2.1.2 on 2018-11-03 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('searchBarApp', '0009_remove_industry_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='industry',
            name='date',
            field=models.DateField(blank=True, default='', null=True),
        ),
    ]
