# Generated by Django 2.1.2 on 2018-11-03 21:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('searchBarApp', '0010_industry_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='industry',
            name='About',
        ),
    ]
