# Generated by Django 2.1.2 on 2018-11-03 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('searchBarApp', '0011_remove_industry_about'),
    ]

    operations = [
        migrations.AddField(
            model_name='industry',
            name='About',
            field=models.CharField(default='', max_length=264),
        ),
    ]
