# Generated by Django 2.1.2 on 2018-11-06 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('searchBarApp', '0012_industry_about'),
    ]

    operations = [
        migrations.AddField(
            model_name='industry',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
