# Generated by Django 2.1.2 on 2018-11-06 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('searchBarApp', '0017_remove_industry_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='industry',
            name='image',
            field=models.FileField(default='', max_length=264, upload_to=''),
        ),
    ]
