# Generated by Django 2.1.2 on 2018-11-06 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('searchBarApp', '0018_industry_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='industry',
            name='image',
            field=models.ImageField(blank=True, upload_to=b'profile_image'),
        ),
    ]
