# Generated by Django 2.1.2 on 2018-11-06 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('searchBarApp', '0019_auto_20181106_2003'),
    ]

    operations = [
        migrations.AddField(
            model_name='industry',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='industry',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
