# Generated by Django 2.1.2 on 2018-11-06 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('searchBarApp', '0020_auto_20181106_2242'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='industry',
            name='image',
        ),
    ]
