# Generated by Django 2.1.2 on 2018-11-17 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('searchBarApp', '0024_industry_count'),
    ]

    operations = [
        migrations.RenameField(
            model_name='industry',
            old_name='category',
            new_name='category',
        ),
        migrations.AlterField(
            model_name='industry',
            name='About',
            field=models.TextField(default=''),
        ),
    ]
