# Generated by Django 2.1.2 on 2018-11-17 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('searchBarApp', '0025_auto_20181117_1830'),
    ]

    operations = [
        migrations.RenameField(
            model_name='industry',
            old_name='category',
            new_name='category',
        ),
    ]
