# Generated by Django 2.1.2 on 2018-11-18 05:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('searchBarApp', '0027_auto_20181117_1835'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='industry',
            name='count',
        ),
        migrations.RemoveField(
            model_name='industry',
            name='image2',
        ),
        migrations.RemoveField(
            model_name='industry',
            name='image3',
        ),
    ]
