# Generated by Django 2.1.2 on 2018-11-18 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('searchBarApp', '0028_auto_20181118_1112'),
    ]

    operations = [
        migrations.AddField(
            model_name='industry',
            name='location',
            field=models.CharField(default='', max_length=528),
        ),
    ]
